version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run-script update
  post_build:
    commands:
      - git config --global user.email "ryan.clark.j@gmail.com"
      - git config --global user.name "Ryan Clark"
      - eval $(./node_modules/.bin/decrypt-kms-env) && git commit -am "$(date -I)" && git remote add ec2s https://${GITHUB_ACCESS_TOKEN}@github.com/rclark/ec2s && git push --set-upstream ec2s gh-pages
